### ISSUE TITLE
Astroconda?

### ISSUE THREAD

**Issue by pllim** [spacetelescope/pylunch#1]
Perhaps @jhunkeler could give a guest lecture on Astroconda. We have been getting some help calls from users switching over from SSBX or Ureka.

**Comment by ivastar** [comment]
That would be great. We are planning to use anaconda already.

**Comment by jhunkeler** [comment]
I'm for it... an interactive Q&A session would probably help some people out.

**Comment by eteq** [comment]
Good idea - Are you around Jul 26, @jhunkeler? And maybe @saraogaz ?  We think both @ivastar and I will be out of town that day, so it would be a good day to have someone else fill in

**Comment by SaOgaz** [comment]
Works for me, I should be around that day.

**Comment by jhunkeler** [comment]
Yes I should be able to make it that day.

**Comment by pllim** [comment]
It might be good to have a chart or something stating the differences between "anaconda", "conda", "astroconda", and "astropy". These terms are similar sounding enough that they can be confusing to people just switching over.

**Comment by jhunkeler** [comment]
![conda_relationship](https://cloud.githubusercontent.com/assets/490981/15879451/5a1cbd4c-2cf2-11e6-9a34-0ff9bafc1a83.PNG)

EDIT:

Or this?

![conda_relationship2](https://cloud.githubusercontent.com/assets/490981/15879596/a211512a-2cf3-11e6-84f9-d4c163a88123.PNG)

**Comment by SaOgaz** [comment]
I kind of feel like these should be going the other way around.... since Conda is the "wrapper" around everything.

**Comment by pllim** [comment]
I agree with @SaraOgaz that the size of the circles should be reversed. Also, I prefer the descriptions used in the second one, except for Astropy, which is more accurately described as, "A Python package that is available in Conda." This is because there are also other non-Conda ways (like PyPi) to obtain Astropy.

**Comment by sosey** [comment]
yah, I kinda feel like it's closer to this:
![slide1](https://cloud.githubusercontent.com/assets/503615/15897391/4a2431d4-2d62-11e6-8c5e-c8e4c9a27fe0.jpg)

**Comment by pllim** [comment]
I think for simplicity, nested circles is better? Although I like the Mickey looking shape.

**Comment by SaOgaz** [comment]
Oh god, no more Mickey's please

**Comment by sosey** [comment]
probably just the way my brain works...I think of the packages as separate from the manager, so conda touches a lot of packages, it has a default package, anaconda. Astropy can also be built as a package, and its part of the default (hence the overlap, but I guess not really a default package, just build and available without us making that conda build). Seperately, Astroconda is a package which also includes astropy. I think I would start nesting circles to show packages installed inside an environment. So for example, if I made an environment and added Astroconda to it,  then I wanted to install a non-conda package with pip, I'd have a circle inside astroconda with "pip install mypackage". Or have another circle off the Conda package manager showing a conda package that wasn't included but available.

**Comment by eteq** [comment]
_Definitely_ agree this should be clarified.  Note that in the first session I described what packages _are_ but only surface-level discussion of the conda vs. astroconda separation.

As for the circles I pretty much agree with @sosey here. These things are mostly distinct and not overlapping - putting them in nested circles implies they do the same thing. 

A lot of people I've talked to (who are new to the whole thing) are confused by the difference between the `anaconda` _channel_ and the anaconda _distribution_, or conflate them together.  Then when you toss in `anaconda`, it's even more confusing because people seem to think it's somehow a _replacement_ for anaconda the distribution, rather than a channel (probably because of the Ureka history?).

The other tricky bit that has led to confusion thus far is that the `anaconda` _channel_ is distinct from the `astroconda` channel.  That is, `conda install astropy` might get you a different package depending on whether or not you have `astroconda` as one of your default channels.

So with that in mind, I think the diagram should be something like this (although mine is quite a bit less aesthetically pleasing...):
EDIT: (note that I realized an error in the original version of this diagram so I've replaced it with a better one - source is [here](https://docs.google.com/drawings/d/10ylhrye4VHS69ghgI13et1sT6C2JfcdcqhhJwhsaeG4/edit?usp=sharing)):
![conda drawing 2](https://cloud.githubusercontent.com/assets/346587/15907088/aab875d8-2d89-11e6-872b-8b4d9af13c1c.png)

**Comment by pllim** [comment]
@Astro-BL , do you like any of these diagrams?

**Comment by pllim** [comment]
Did we already cover this?

**Comment by eteq** [comment]
I think @jhunkeler presented it at one point?  I wasn't here that week, but I know we at least planned it at one point.

**Comment by sosey** [comment]
Yah, I'm pretty sure I remember him presenting astroconda

**Comment by pllim** [comment]
Okay. Closing then.
