### ISSUE TITLE
Add shift+enter command to Jupyter Notebook section of the session 2 workflow

### ISSUE THREAD

**Issue by kjbrooks** [spacetelescope/pylunch#3]
In the workflow for session 2, for Jupiter Notebook, a line should be added to telling users that to execute code in the notebook, they should press shift+enter.

**Comment by eteq** [comment]
Thanks @kjbrooks, good suggestion - I updated it in the notebook via commit 8daf26b

One tip in case something like this comes up again: for something like this you might be able to just use github's built-in edit feature, @kjbrooks - if you find the file in question in github there's a little "edit" icon in the upper-right.  You can use that to automatically create a pull request, which will suggest whatever change you make in the edit.  For something complex in a notebook that's usually inconvenient (because the notebook is a special JSON format), but for wording changes like this you can usually get away with just editing the sentence in the relevant part of hte file.
